# Generated by Django 2.2.5 on 2020-04-24 12:07

from django.db import migrations
import django_resized.forms
import predict.models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploads',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 500], storage=predict.models.OverwriteStorage(), upload_to='uploaded_images/'),
        ),
    ]
